services:
  next-app:
    container_name: AI-Face-Swap-V3
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080
    networks:
      - dokploy-network
    labels:
      # 启用 traefik
      - "traefik.enable=true"
      # HTTP 路由配置（处理 HTTP 请求）
      - "traefik.http.routers.my-nextjs-app-http.rule=Host(`aifaceswap.app`) || Host(`www.aifaceswap.app`)"
      - "traefik.http.routers.my-nextjs-app-http.entrypoints=web"
      - "traefik.http.routers.my-nextjs-app-http.middlewares=https-redirect"
      # HTTPS 路由配置（处理 HTTPS 请求）
      - "traefik.http.routers.my-nextjs-app.rule=Host(`aifaceswap.app`) || Host(`www.aifaceswap.app`)"
      - "traefik.http.routers.my-nextjs-app.entrypoints=websecure"
      - "traefik.http.routers.my-nextjs-app.tls.certResolver=letsencrypt"
      # 服务端口配置
      - "traefik.http.services.my-nextjs-app.loadbalancer.server.port=8080"
      # 重定向配置
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
    deploy:
      resources:
        limits:
          memory: 1G
networks:
  dokploy-network:
    external: true
